package org.dyndns.schuschu.xmms2client.action.base;

import org.eclipse.swt.SWT;

public enum FooKey {
	//TODO: add all the other
	//NONE(0), CR(SWT.CR), DEL(SWT.DEL), ESC(SWT.ESC);
	
	ALT(SWT.ALT),
	ARROW_DOWN(SWT.ARROW_DOWN),
	ARROW_LEFT(SWT.ARROW_LEFT),
	ARROW_RIGHT(SWT.ARROW_RIGHT),
	ARROW_UP(SWT.ARROW_UP),
	BREAK(SWT.BREAK),
	BUTTON_MASK(SWT.BUTTON_MASK),
	BUTTON1(SWT.BUTTON1),
	BUTTON2(SWT.BUTTON2),
	BUTTON3(SWT.BUTTON3),
	BUTTON4(SWT.BUTTON4),
	BUTTON5(SWT.BUTTON5),
	CAPS_LOCK(SWT.CAPS_LOCK),
	COMMAND(SWT.COMMAND),
	CONTROL(SWT.CONTROL),
	CTRL(SWT.CTRL),
	END(SWT.END),
	F1(SWT.F1),
	F10(SWT.F10),
	F11(SWT.F11),
	F12(SWT.F12),
	F13(SWT.F13),
	F14(SWT.F14),
	F15(SWT.F15),
	F2(SWT.F2),
	F3(SWT.F3),
	F4(SWT.F4),
	F5(SWT.F5),
	F6(SWT.F6),
	F7(SWT.F7),
	F8(SWT.F8),
	F9(SWT.F9),
	HELP(SWT.HELP),
	HOME(SWT.HOME),
	INSERT(SWT.INSERT),
	KEYPAD_0(SWT.KEYPAD_0),
	KEYPAD_1(SWT.KEYPAD_1),
	KEYPAD_2(SWT.KEYPAD_2),
	KEYPAD_3(SWT.KEYPAD_3),
	KEYPAD_4(SWT.KEYPAD_4),
	KEYPAD_5(SWT.KEYPAD_5),
	KEYPAD_6(SWT.KEYPAD_6),
	KEYPAD_7(SWT.KEYPAD_7),
	KEYPAD_8(SWT.KEYPAD_8),
	KEYPAD_9(SWT.KEYPAD_9),
	KEYPAD_ADD(SWT.KEYPAD_ADD),
	KEYPAD_CR(SWT.KEYPAD_CR),
	KEYPAD_DECIMAL(SWT.KEYPAD_DECIMAL),
	KEYPAD_DIVIDE(SWT.KEYPAD_DIVIDE),
	KEYPAD_EQUAL(SWT.KEYPAD_EQUAL),
	KEYPAD_MULTIPLY(SWT.KEYPAD_MULTIPLY),
	KEYPAD_SUBTRACT(SWT.KEYPAD_SUBTRACT),
	MOD1(SWT.MOD1),
	MOD2(SWT.MOD2),
	MOD3(SWT.MOD3),
	MOD4(SWT.MOD4),
	MODIFIER_MASK(SWT.MODIFIER_MASK),
	NUM_LOCK(SWT.NUM_LOCK),
	PAGE_DOWN(SWT.PAGE_DOWN),
	PAGE_UP(SWT.PAGE_UP),
	PAUSE(SWT.PAUSE),
	PRINT_SCREEN(SWT.PRINT_SCREEN),
	SCROLL_LOCK(SWT.SCROLL_LOCK),
	SHIFT(SWT.SHIFT);

	private int code;

	private FooKey(int code) {
		this.code = code;
	}

	public int getCode() {
		return code;
	}
}
